// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE0EPSS01fSkaCXaHMmKpqyqX7JGH0LWw',
    appId: '1:457939571138:web:fee84df774a3d42e7a865b',
    messagingSenderId: '457939571138',
    projectId: 'my-note-925d9',
    authDomain: 'my-note-925d9.firebaseapp.com',
    storageBucket: 'my-note-925d9.firebasestorage.app',
    measurementId: 'G-8Z1VTKY42S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoR1qhn16PK2Uzta6dJFUPvLAY2Q24e_c',
    appId: '1:457939571138:android:7689448a58a906687a865b',
    messagingSenderId: '457939571138',
    projectId: 'my-note-925d9',
    storageBucket: 'my-note-925d9.firebasestorage.app',
  );
}
